spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  liquibase:
    contexts: prod

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
