name: ecom-stack
services:
  gateway-user:
    image: ecom-user:0.0.1-SNAPSHOT
    environment:
        - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ecommerce?schema=ecom_user
        - SPRING_CLOUD_CONSUL_HOST=consul
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ecom-network
    deploy:
      replicas: 1

  order:
    image: ecom-order:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ecommerce?schema=ecom_order
      - SPRING_CLOUD_CONSUL_HOST=consul
      - STRIPE_API_KEY=sk_test_51PqP6gFxB2dnnKdDBIOlrdijvUWhqT5ZqiYvxuHnZ4slJH8oN6oZ7n4e3anF4d5tcR8HR0QmGecaVN1APcswCRqt002ls2xKIV
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8082/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ecom-network
    deploy:
      replicas: 1

  product:
    image: ecom-product:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ecommerce?schema=ecom_product
      - SPRING_CLOUD_CONSUL_HOST=consul
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ecom-network

  postgresql:
    extends:
      file: ./postgresql.yml
      service: database
    networks:
      - ecom-network
  consul:
    extends:
      file: ./consul.yml
      service: consul
    networks:
     - ecom-network
  zipkin:
    extends:
      file: ./zipkin.yml
      service: zipkin
    networks:
      - ecom-network

networks:
  ecom-network:
    external: false
    name: ecom-network
