name: consul-ecom
services:
  consul:
    image: hashicorp/consul:1.20.0
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600"
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO -config-dir=/consul/config
    volumes:
      - './consul-config:/consul/config'
    healthcheck:
      # return information about the status of the Consul cluster https://www.consul.io/api/status.html
      test: [ "CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader" ]
      interval: 1s
      timeout: 3s
      retries: 60
