name: elk-ecom
services :
    setup:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
      container_name: setup
      command:
        - bash
        - -c
        - |
          echo "Waiting for Elasticsearch availability";
          until curl -s http://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
          echo "Setting kibana_system password";
          until curl -s -X POST -u "elastic:codecake" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"codecake\"}" | grep -q "^{}"; do sleep 10; done;
          echo "All done!";

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
      # give the container a name
      # this will also set the container's hostname as elasticsearch
      container_name: elasticsearch
      # this will store the data permanently outside the elastissearch container
      volumes:
        - ./elk/elastic:/usr/share/elasticsearch/data
      # this will allow access to the content from outside the container
      ports:
        - "9200:9200"
      environment:
        - discovery.type=single-node
        - cluster.name=elasticsearch
        - bootstrap.memory_lock=true
        # limits elasticsearch to 1 GB of RAM
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        # The password for the 'elastic' user
        - ELASTIC_PASSWORD=codecake
        - xpack.security.http.ssl.enabled=false
        - xpack.security.enabled=true

    kibana:
      image: docker.elastic.co/kibana/kibana:8.15.1
      container_name: kibana
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - ELASTICSEARCH_USERNAME=kibana_system
        - ELASTICSEARCH_PASSWORD=codecake
        - TELEMETRY_ENABLED=false
      volumes:
        - ./elk/kibana:/usr/share/kibana/config
      depends_on:
        - elasticsearch

    logstash:
      image: docker.elastic.co/logstash/logstash:8.15.1
      container_name: logstash
      environment:
        - ELASTICSEARCH_HOST=elasticsearch
        - ELASTICSEARCH_PORT=9200
        - ELASTICSEARCH_USERNAME=elastic
        - ELASTICSEARCH_PASSWORD=codecake
      volumes:
        - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
      ports:
        - "5000:5000"
      depends_on:
        - elasticsearch
