name: pg-ecom
services:
   database:
     image: 'postgres:latest'
     ports:
       - '5432:5432'
     environment:
      - 'POSTGRES_USER=codecake'
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=codecake'
     volumes:
      - '~/volumes/codecake-yt/postgres:/var/lib/postgresql/data'
     healthcheck:
       test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
       interval: 5s
       timeout: 5s
       retries: 10
     networks:
       - ecom-network

